const { test } = require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const os=require('os');const {TaskRepository}=require('../src/services/taskRepository');
const png1x1=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
function setup(t,io=fs){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'yanqian-recovery-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return {directory,repo:new TaskRepository({directory,fs:io})};}
test('missing primary restores latest backup rather than silently seeding',t=>{const {directory,repo}=setup(t);repo.command('add',{content:'saved'});repo.backup();fs.renameSync(repo.file,repo.file+'.moved');const next=new TaskRepository({directory});assert.equal(next.snapshot().todoList[0]?.content,'saved');assert.ok(next.recoveryNotice);});
test('malformed undo and trash positions are rejected before import',t=>{const {directory,repo}=setup(t);const original=repo.snapshot();const file=path.join(directory,'bad.json');for(const extra of [{lastCompletion:{id:'missing',index:'bad'}},{trashList:[{list:'todoList',index:'bad',task:{id:'x',content:'test'}}]}]){fs.writeFileSync(file,JSON.stringify({...original,...extra}));assert.throws(()=>repo.importFrom(file));assert.deepEqual(repo.snapshot(),original);}});
test('completion failure at primary rename leaves state unchanged after successful backup',t=>{let fail=false;let target;const io=Object.create(fs);io.renameSync=(src,dest)=>{if(fail&&dest===target)throw Error('primary replacement failed');return fs.renameSync(src,dest);};const {directory,repo}=setup(t,io);target=repo.file;const id=repo.command('add',{content:'safe'}).todoList[0].id;const before=repo.snapshot();fail=true;assert.throws(()=>repo.command('complete',{id}),/primary replacement/);assert.deepEqual(repo.snapshot(),before);assert.deepEqual(new TaskRepository({directory}).snapshot(),before);});
test('recovery stops on failure writing newest valid backup instead of restoring older data',t=>{const {directory,repo}=setup(t);repo.command('add',{content:'old'});repo.backup();repo.command('add',{content:'new'});repo.backup();fs.writeFileSync(repo.file,'corrupt');let attempts=0;const io=Object.create(fs);io.renameSync=(src,dest)=>{if(dest===repo.file && ++attempts===1)throw Error('write unavailable');return fs.renameSync(src,dest);};assert.throws(()=>new TaskRepository({directory,fs:io}),/write unavailable/);assert.equal(attempts,1);assert.equal(fs.readFileSync(repo.file,'utf8'),'corrupt');});
test('startup recovery can replace broken primary from external backup preserving original bytes and screenshots',t=>{const {directory,repo}=setup(t);const {restoreDataFile}=require('../src/services/taskRepository');assert.equal(typeof restoreDataFile,'function');const id=repo.command('add',{content:'external backup'}).todoList[0].id;repo.addScreenshot({list:'todoList',taskId:id,png:png1x1});const backup=path.join(directory,'external.json');repo.exportTo(backup);fs.writeFileSync(repo.file,'broken primary');restoreDataFile({directory,source:backup});const next=new TaskRepository({directory});const task=next.snapshot().todoList[0];assert.equal(task.content,'external backup');assert.deepEqual(next.readScreenshot({list:'todoList',taskId:task.id,screenshotId:task.screenshots[0].id}),png1x1);assert.ok(fs.readdirSync(path.join(directory,'safety')).some(name=>fs.readFileSync(path.join(directory,'safety',name),'utf8')==='broken primary'));});
test('invalid external startup backup never changes the broken primary',t=>{const {directory,repo}=setup(t);const {restoreDataFile}=require('../src/services/taskRepository');assert.equal(typeof restoreDataFile,'function');const backup=path.join(directory,'invalid.json');fs.writeFileSync(backup,'{}');fs.writeFileSync(repo.file,'broken primary');assert.throws(()=>restoreDataFile({directory,source:backup}));assert.equal(fs.readFileSync(repo.file,'utf8'),'broken primary');});
test('invalid imported date fields cannot break Done grouping or replace live data',t=>{const {directory,repo}=setup(t);const before=repo.snapshot();const file=path.join(directory,'bad-date.json');fs.writeFileSync(file,JSON.stringify({todoList:[],doneList:[{content:'A',todo_date:123},{content:'B',done_date:'2026/09/05'}]}));assert.throws(()=>repo.importFrom(file));assert.deepEqual(repo.snapshot(),before);});
